/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as CadastroClienteRouteImport } from './routes/cadastro-cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackClienteIdRouteImport } from './routes/feedback.$clienteId'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated.notas'
import { Route as AuthenticatedFeedbacksRouteImport } from './routes/_authenticated.feedbacks'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedServicosIndexRouteImport } from './routes/_authenticated.servicos.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated.clientes.index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated.clientes.$id'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroClienteRoute = CadastroClienteRouteImport.update({
  id: '/cadastro-cliente',
  path: '/cadastro-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackClienteIdRoute = FeedbackClienteIdRouteImport.update({
  id: '/feedback/$clienteId',
  path: '/feedback/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedbacksRoute = AuthenticatedFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicosIndexRoute =
  AuthenticatedServicosIndexRouteImport.update({
    id: '/servicos/',
    path: '/servicos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/feedback/$clienteId': typeof FeedbackClienteIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/servicos/': typeof AuthenticatedServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/feedback/$clienteId': typeof FeedbackClienteIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/servicos': typeof AuthenticatedServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro-cliente': typeof CadastroClienteRoute
  '/portal': typeof PortalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/feedback/$clienteId': typeof FeedbackClienteIdRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/servicos/': typeof AuthenticatedServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro-cliente'
    | '/portal'
    | '/dashboard'
    | '/feedbacks'
    | '/notas'
    | '/feedback/$clienteId'
    | '/clientes/$id'
    | '/clientes/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro-cliente'
    | '/portal'
    | '/dashboard'
    | '/feedbacks'
    | '/notas'
    | '/feedback/$clienteId'
    | '/clientes/$id'
    | '/clientes'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro-cliente'
    | '/portal'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedbacks'
    | '/_authenticated/notas'
    | '/feedback/$clienteId'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/'
    | '/_authenticated/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroClienteRoute: typeof CadastroClienteRoute
  PortalRoute: typeof PortalRoute
  FeedbackClienteIdRoute: typeof FeedbackClienteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-cliente': {
      id: '/cadastro-cliente'
      path: '/cadastro-cliente'
      fullPath: '/cadastro-cliente'
      preLoaderRoute: typeof CadastroClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$clienteId': {
      id: '/feedback/$clienteId'
      path: '/feedback/$clienteId'
      fullPath: '/feedback/$clienteId'
      preLoaderRoute: typeof FeedbackClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedbacks': {
      id: '/_authenticated/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AuthenticatedFeedbacksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servicos/': {
      id: '/_authenticated/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof AuthenticatedServicosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbacksRoute: typeof AuthenticatedFeedbacksRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedServicosIndexRoute: typeof AuthenticatedServicosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbacksRoute: AuthenticatedFeedbacksRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedServicosIndexRoute: AuthenticatedServicosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroClienteRoute: CadastroClienteRoute,
  PortalRoute: PortalRoute,
  FeedbackClienteIdRoute: FeedbackClienteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
